EPOCH_MS_DEFAULT = 1288834974657
NODE_ID_DEFAULT = 0
TIMESTAMP_BITS, NODE_ID_BITS, SEQUENCE_ID_BITS = 41, 10, 12
TIMESTAMP_MS_MAX = 2**TIMESTAMP_BITS - 1
NODE_ID_MAX = 2**NODE_ID_BITS - 1
SEQUENCE_ID_MAX = 2**SEQUENCE_ID_BITS - 1
NODE_ID_SHIFT = SEQUENCE_ID_BITS
TIMESTAMP_SHIFT = SEQUENCE_ID_BITS + NODE_ID_BITS
